/**
 * generate-questions.ts
 * ─────────────────────────────────────────────────────────────────
 * Reads all PDF files from the data/ folder, sends their text to
 * Grok (xAI API), and writes the generated questions to
 * data/questions.ts  — overwriting whatever was there before.
 *
 * USAGE (one-time setup):
 *   npm install -g ts-node          (if not installed)
 *   npm install pdf-parse            (add to devDependencies)
 *
 * RUN:
 *   GROK_API_KEY=your_key ts-node scripts/generate-questions.ts
 *   (Windows PowerShell:)
 *   $env:GROK_API_KEY="your_key"; npx ts-node scripts/generate-questions.ts
 *
 * ─────────────────────────────────────────────────────────────────
 */

import fs from 'fs';
import path from 'path';

// ── Config ────────────────────────────────────────────────────────
const DATA_DIR    = path.join(__dirname, '..', 'data');
const OUTPUT_FILE = path.join(DATA_DIR, 'questions.ts');
const API_KEY     = process.env.GROK_API_KEY ?? '';
const GROK_URL    = 'https://api.x.ai/v1/chat/completions';
const MODEL       = 'grok-3-mini'; // or 'grok-3' for higher quality
const NUM_QUESTIONS = 30;          // how many Q&As to generate

if (!API_KEY) {
  console.error('❌  Please set GROK_API_KEY environment variable.');
  process.exit(1);
}

// ── 1. Read all PDFs from data/ ───────────────────────────────────
async function extractTextFromPDFs(): Promise<string> {
  // Dynamic import so ts-node can resolve it
  const pdfParse = (await import('pdf-parse')).default;
  const pdfFiles = fs.readdirSync(DATA_DIR).filter(f => f.endsWith('.pdf'));

  if (pdfFiles.length === 0) {
    console.error(`❌  No PDF files found in ${DATA_DIR}`);
    console.error('     Drop your PDF files into the data/ folder and re-run.');
    process.exit(1);
  }

  console.log(`📂  Found ${pdfFiles.length} PDF(s): ${pdfFiles.join(', ')}`);

  let combined = '';
  for (const file of pdfFiles) {
    const buffer = fs.readFileSync(path.join(DATA_DIR, file));
    const result = await pdfParse(buffer);
    combined += `\n\n--- From file: ${file} ---\n` + result.text;
  }
  return combined;
}

// ── 2. Build the prompt ───────────────────────────────────────────
function buildPrompt(documentText: string): string {
  // Truncate to ~40k chars to stay within context limits
  const excerpt = documentText.slice(0, 40_000);

  return `
You are an expert quiz generator.

Based on the following document(s) about React Native, generate exactly ${NUM_QUESTIONS} multiple-choice questions.

Rules:
- Each question must have exactly 4 options.
- Clearly mark the correct option index (0-based).
- Provide a short, clear explanation of the correct answer.
- Questions should range from beginner to advanced.
- Return ONLY a valid JSON array. No markdown, no extra text.

JSON format:
[
  {
    "id": "q1",
    "text": "Question text here?",
    "options": ["Option A", "Option B", "Option C", "Option D"],
    "correctAnswerIndex": 0,
    "explanation": "Short explanation why this is correct."
  }
]

Document content:
${excerpt}
  `.trim();
}

// ── 3. Call Grok API ──────────────────────────────────────────────
async function callGrok(prompt: string): Promise<string> {
  console.log('🤖  Calling Grok API...');

  const response = await fetch(GROK_URL, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Authorization': `Bearer ${API_KEY}`,
    },
    body: JSON.stringify({
      model: MODEL,
      messages: [
        { role: 'system', content: 'You are a quiz generator. Return valid JSON only.' },
        { role: 'user',   content: prompt },
      ],
      temperature: 0.7,
    }),
  });

  if (!response.ok) {
    const err = await response.text();
    console.error('❌  Grok API error:', err);
    process.exit(1);
  }

  const data = await response.json() as any;
  return data.choices[0].message.content as string;
}

// ── 4. Parse & write questions.ts ────────────────────────────────
function writeQuestionsFile(jsonString: string) {
  // Strip any accidental markdown code fences
  const clean = jsonString.replace(/```json|```/g, '').trim();

  let parsed: object[];
  try {
    parsed = JSON.parse(clean);
  } catch (e) {
    console.error('❌  Failed to parse Grok response as JSON. Raw response:');
    console.error(jsonString.slice(0, 500));
    process.exit(1);
  }

  const fileContent = `import { Question } from '../types';

/**
 * Auto-generated by scripts/generate-questions.ts using Grok AI.
 * Do not edit manually — re-run the script to regenerate.
 */
export const reactNativeQuestions: Question[] = ${JSON.stringify(parsed, null, 2)};
`;

  fs.writeFileSync(OUTPUT_FILE, fileContent, 'utf-8');
  console.log(`✅  Wrote ${parsed.length} questions to ${OUTPUT_FILE}`);
}

// ── Main ──────────────────────────────────────────────────────────
(async () => {
  try {
    const text = await extractTextFromPDFs();
    const prompt = buildPrompt(text);
    const raw = await callGrok(prompt);
    writeQuestionsFile(raw);
    console.log('🎉  Done! Run your app — quiz questions are ready.');
  } catch (err) {
    console.error('Unexpected error:', err);
    process.exit(1);
  }
})();
